#!/bin/bash
set -x
PID=$1
namespace="${PID}_ns"
NUM=$2

ip netns exec ${namespace} ip a

ip netns exec ${namespace} ip link set veth${NUM}-con down
ip link set veth${NUM}-br down
ip link set bridge0 down

ip netns exec ${namespace} ip link del veth${NUM}-con
ip link del veth${NUM}-br
ip netns delete ${namespace}
brctl delbr bridge0

umount /var/run/netns/${namespace}


