#!/bin/bash

ip netns exec container ip link set veth1-con down
ip link set veth1-host down
ip link set bridge0 down

ip netns exec container ip link del veth1-con
ip netns delete container
ip link del veth1-host
brctl delbr bridge0


