#!/bin/bash
set -x

#make interface
ip link add veth0-host type veth peer name veth0-con

#make namespace
ip netns add container

#set interface to namespace
ip link set veth0-con netns container

#attach ip
ip addr add 10.10.10.10/24 dev veth0-host
ip netns exec container ip addr add 10.10.10.11/24 dev veth0-con

#exec interface
ip link set veth0-host up
ip netns exec container ip link set veth0-con up
ip netns exec container ip link set lo up

#set routing
ip netns exec container ip route add default via 10.10.10.10

#add NAPT
iptables --table nat --flush
iptables --table nat --append POSTROUTING --source 10.10.10.0/24 --jump MASQUERADE
iptables -A FORWARD -o eth0 -i veth0-host -j ACCEPT
iptables -A FORWARD -i eth0 -o veth0-host -j ACCEPT
