#!/bin/bash
set -x

#make interface
ip link add veth1-host type veth peer name veth1-con

#make namespace
ip netns add container

#set interface to namespace
ip link set veth1-con netns container

#attach ip
ip addr add 10.10.10.10/24 dev veth1-host
ip netns exec container ip addr add 10.10.10.11/24 dev veth1-con

#exec interface
ip link set veth1-host up
ip netns exec container ip link set veth1-con up
ip netns exec container ip link set lo up

#set routing
ip netns exec container ip route add default via 10.10.10.10

#add NAPT
iptables --table nat --flush
iptables --table nat --append POSTROUTING --source 10.10.10.0/24 --jump MASQUERADE
