#!/bin/bash

#make interface
ip link add name veth1-con type veth peer name veth1-host

#make namespace
ip netns add container

#set interface to namespace
ip link set veth1-con netns container

#make bridge
brctl addbr bridge0
brctl addif bridge0 veth1-host

#attach ip
ip addr add 10.10.10.10/24 dev veth1-host
ip netns exec container ip addr add 10.10.10.11/24 dev veth1-con

#exec interface
ip link set bridge0 up
ip link set veth1-host up
ip netns exec container ip link set veth1-con up
ip netns exec container ip link set lo up
#set NAT
ip netns exec container ip route add default via 10.10.10.10

#add routing
iptables --table nat --flush
iptables --table nat --append POSTROUTING --source 10.10.10.0/24 -o eth0 --jump MASQUERADE

#eth0 add to bridge and attach ip to eth0
#brctl addif bridge0 eth0
#sleep 20s
#ip addr add 133.242.232.245/24 dev eth0
